### PR TITLE
Use specific printer driver

### PR DESCRIPTION
**Pull request by jabley**
Using the preferred printer driver should give better printer output,
and allow printer-specific options to be used when configuring.
This change gives more control to the end user.

Note: the driver may need to be installed via munki, in which case we
should not merge this. Not everyone currently has a managed machine.

### CODE REVIEW

**Comment by dcarley** [comment]
You forgot to say "why"

**Comment by jabley** [comment]
Rebased and force-pushed with marginally fuller commit message. Thanks @dcarley.

**Comment by mattbostock** [comment]
It think it'd be a good idea to feature-flag this, so that those wishing to can fall back to the generic driver. For example, I don't print enough for me to want to spend time installing drivers.

**Comment by dcarley** [comment]
> Using the preferred printer driver should give better printer output,
> and allow printer-specific options to be used when configuring.
> This change gives more control to the end user.

Can you give some examples?

An opt-in feature flag sounds like a good idea. The generic drivers is fine for my needs.

**Comment by annashipman** [comment]
+1 to making this opt-in; I print quite a bit and the generic driver has been fine for me.

**Comment by ajlanghorn** [comment]
I feature-flagged this in @jabley's absence.

**Pull request merged**
