### PR TITLE
pull in 10.11 El Capitan support

### PR DESCRIPTION
**Pull request by bazbremner**
**Opening for visibility**, I'm not expecting an immediate merge...

Because I occasionally like burying myself under a pile of yaks I've updated to OS X El Capitan and updated gds-boxen/homebrew to keep up.

This PR merges github/our-boxen to bring us up to date and then bumps the boxen gem from 2.7.2 to 2.8.0 to include 10.11 as a supported OS.

The only issue I've encountered so far is with node installs - the newer boxen-nodejs module no longer expects a leading `v` when specifying versions, so I had to make the following change to my personal manifest:

```diff
-  class { 'nodejs::global': version => 'v0.12.7' }
+  class { 'nodejs::global': version => '0.12.7' }
```

I have _not_ included the nodeJS tweak in this branch.

### CODE REVIEW

**Comment by bradwright** [comment]
I think we probably need to do this.

**Comment by KushalP** [comment]
I've just reviewed this. Here's what I did:

1. Ran `boxen` locally to make sure I was running against master `[no change]`
2. Merged this branch into my local branch
3. Ran `boxen` with this branch

From my local machine changes I'm going to say that this was all fine. However my config might not be as colourful as other people's configs.

I'd say this is fine to merge in, but give it a day for others to throw in their thoughts.

**Comment by bazbremner** [comment]
My commit 97e4e1e duplicates https://github.com/boxen/our-boxen/commit/74e3455e865337f18d4f516fa989f61ba459b1cf that's on our-boxen's master, but boxen hasn't moved much since I opened this PR.

**Comment by bradwright** [comment]
@bazbremner could you merge the upstream Boxen (even if it's a no-op) just so future updates are easier? Then I think we can merge this.

**Comment by bradwright** [comment]
Did the merge myself :+1:

**Comment by bazbremner** [comment]
@bradwright ah, excellent. Beat me to it.

**Comment by jabley** [comment]
Also breaks `nodejs::module` usage. /cc @timmow @leenagupte 

```diff
diff --git a/modules/people/manifests/jabley.pp b/modules/people/manifests/jabley.pp
index c60e5d7..3b039a9 100644
--- a/modules/people/manifests/jabley.pp
+++ b/modules/people/manifests/jabley.pp
@@ -212,7 +212,7 @@ class people::jabley(
 
   nodejs::version { 'v0.12.2': }
 
-  nodejs::module { [
+  npm_module { [
     'express-generator',
     'jsontool',
     'grunt-cli',
@@ -222,7 +222,7 @@ class people::jabley(
     'stackvis',
     'tick',
     ]:
-    node_version => $node_version,
+    node_version => '*',
   }
 
   $home = "/Users/${::luser}"
```

**Comment by bazbremner** [comment]
@jabley yup, note my original comment.

**Pull request merged**
