### PR TITLE
Make version of gds_virtualbox configurable

### PR DESCRIPTION
**Pull request by heathd**
note that it will not auto-upgrade as the pkgdmg provider does not support versioning.

You'll need to remove /var/db/.puppet_pkgdmg_installed_VirtualBox to force an upgrade

### CODE REVIEW

**Comment by bradleywright** [comment]
If we're not including https://github.com/alphagov/gds-boxen/blob/master/modules/gds_virtualbox/manifests/recommended.pp we should delete it.

**Comment by heathd** [comment]
I think some people's individual manifests include it directly, which is why I left it there.

**Comment by heathd** [comment]
I may be mistaken.. will check

**Comment by heathd** [comment]
you were right.. removed

**Pull request merged**
