### PR TITLE
Tidy SSH config

### PR DESCRIPTION
**Pull request by mattbostock**
Please see commit messages for details.

### CODE REVIEW

**Comment by rjw1** [comment]
i thought it was most specific it matched not first.

**Comment by mattbostock** [comment]
> For each parameter, the first obtained value will be used.  The configuration files contain sections
     separated by ``Host'' specifications, and that section is only applied for hosts that match one of the
     patterns given in the specification.  The matched host name is the one given on the command line.

>    Since the first obtained value for each parameter is used, more host-specific declarations should be
     given near the beginning of the file, and general defaults at the end.

**Comment by rjw1** [comment]
ooh!
also that apple man page is unreadable :)

http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man5/ssh_config.5?query=ssh_config&arch=i386 is much more readable

**Comment by mattbostock** [comment]
Without a doubt, but I'm not currently running OpenBSD on my Mac :-)

**Comment by bradleywright** [comment]
Merge or not?

**Comment by alexmuller** [comment]
This seems to fail quite horribly for me on OS X 10.9.5 so I'd rather we didn't merge it.

**Comment by alexmuller** [comment]
```bash
[HOST] 09:25:45 ~ $ bash --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
[HOST] 09:25:53 ~ $ ssh -V
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
[HOST] 09:26:00 ~ $ ssh backend-1.backend.preview
/bin/bash: fork: Resource temporarily unavailable
/bin/bash: fork: Resource temporarily unavailable
/bin/bash: fork: Resource temporarily unavailable
ssh_exchange_identification: Connection closed by remote host
(followed by the same line repeated 613 more times)
```

**Comment by mattbostock** [comment]
Admittedly I don't use this configuration, but wanted to remove the unnecessary key-forwarding for the CI server in the interest of security.

I think the error seen by @alexmuller might be an ordering issue (where the jumpbox is used as a proxy to the jumpbox over and over); I'll have a look into that.

**Comment by mattbostock** [comment]
@alexmuller: It seems the error you reported also happens on `master`?

**Comment by mattbostock** [comment]
I think that error is caused by the fact that the jumpbox is set set to `ci-master.ci-govuk`, which triggers a loop.

**Comment by alexmuller** [comment]
Hm, I can't reproduce this error on master. Everything's working as I expect.

**Comment by mattbostock** [comment]
@alexmuller: I've pushed some changes which I've been testing this using:

```bash
ssh -v -F modules/gds_ssh_config/files/gds_ssh_config <user>@<host>
```

Could you please give it a try?

**Comment by alexmuller** [comment]
Boxen has applied this diff:

```
 # Preview
 # -------
 Host jumpbox-1.management.preview
   Hostname jumpbox.preview.alphagov.co.uk
-  ProxyCommand none
 
 Host jumpbox-2.management.preview
   Hostname jumpbox.preview.alphagov.co.uk
   Port     1022
-  ProxyCommand none
 
 Host *.preview
-  ProxyCommand ssh -e none %r@jumpbox-1.management.preview -W $(echo %h | sed 's/\.preview$//'):%p
+  ProxyCommand ssh %r@jumpbox-1.management.preview -W $(echo %h | sed 's/\.preview$//'):%p
```

But I still get the same issue unfortunately :(

**Comment by mattbostock** [comment]
The most useful part of this PR (avoid the use of key forwarding) has been implemented in https://github.com/alphagov/gds-boxen/pull/155

**Comment by dcarley** [comment]
Sorry, didn't see this :dancer:

**Comment by mattbostock** [comment]
No need for apologies, glad it finally got implemented :dancers:

**Pull request closed without merging**
