### PR TITLE
Caroline manifest

### PR DESCRIPTION
**Pull request by carolinegreen**
Added manifest file.

### CODE REVIEW

**Comment by jabley** [comment]
Not sure this merges cleanly?

**Comment by ajlanghorn** [comment]
@carolinegreen Do you still want this merging, or would you like it to be closed? We can't merge it until it merges cleanly, so there's probably some work to do.

**Comment by mattbostock** [comment]
I'm going to close this pull request for now as it's been open for some time.

@carolinegreen Don't hesitate to ask if you'd like to pair to rebase this and push your changes to master.

**Comment by carolinegreen** [comment]
Hello, thanks I have rebased it now, and have opened a new pull request.

**Comment by mattbostock** [comment]
:+1:

**Pull request closed without merging**
