### PR TITLE
Upgrade gcc and git for xcode 6.3.1

### PR DESCRIPTION
**Pull request by daibach**
This commit updates gcc to version 2.2.1 and git to 2.7.8 so that it works with xcode 6.3.1 on yosemite.

This was the suggested fix for the issue upstream at https://github.com/boxen/our-boxen/issues/741

Hopefully this will resolve issue #156

### CODE REVIEW

**Comment by mattbostock** [comment]
LGTM, though I'll let somebody who's in a position to test this to merge.

**Comment by daibach** [comment]
I've successfully run this on a new build Yosemite with xcode 6.3.1, but not sure how this affects anyone using xcode 6.2 or Mavericks. Anyone able to test these?

**Comment by bradleywright** [comment]
This appears to work fine for @aleksdrozdov as well, who is running Yosemite. I suggest we merge this as all new Macs issued are currently blocked by this bug.

**Comment by samjsharpe** [comment]
You should just merge https://github.com/alphagov/gds-boxen/pull/162 instead then and close this ;)

**Comment by daibach** [comment]
Too late now, but this seems to work for me on a slightly older Yosemite build.

**Pull request closed without merging**
