### PR TITLE
Upgrade vagrant to the latest available version

### PR DESCRIPTION
**Pull request by timmow**
This has been out for a while now and fixes various bugs.

### CODE REVIEW

**Comment by timmow** [comment]
I've tested this with the performance platform dev vm - I know others tend to upgrade vagrant outside of boxen, so has anyone had issues with 1.7.2?

**Comment by mattbostock** [comment]
:+:1

**Comment by timmow** [comment]
I ran into [this issue](https://github.com/mitchellh/vagrant/pull/5325) - we define 2 private networks on the perf platform vm

Removing all the vagrant lines from `/etc/network/interfaces` and restarting the vm did fix the issue - will update if I see this happening again

**Comment by samjsharpe** [comment]
I use 1.7.2 and have for a while with no problems. :+1: for merging this as long as it's OK with you Tim.

**Comment by timmow** [comment]
:+1:

**Pull request merged**
