### PR TITLE
Upgrade Vagrant module 3.3.0 -> 3.3.4

### PR DESCRIPTION
**Pull request by dcarley**
I need to install Vagrant 1.8.x, which isn't supported by the current
version of this module that we're using because newer releases are only
hosted on `releases.hashicorp.com` and not `dl.bintray.com`. The new URL
does also include old releases.

The new version of this module also changes the default version of Vagrant,
if you don't specify `version` param, from 1.7.2 to 1.8.0. This will affect
anyone that uses `include vagrant` in their people manifest. I'll ping those
people on the pull request.

Full list of changes:

- boxen/puppet-vagrant@3.3.0...3.3.4

/cc @alexmuller @annashipman @bruntonspall @carlmassa @daibach @danielroseman @deanwilson @issyl0 @JohnStrudwick @mattbostock @philandstuff @rboulton @rjw1 @surminus @tombooth

### CODE REVIEW

**Comment by mattbostock** [comment]
:+1: for me.

**Comment by issyl0** [comment]
:+1:, I suppose.

**Comment by JohnStrudwick** [comment]
:+1:  I don't use Boxen on my latest machine anyway

**Comment by alexmuller** [comment]
https://github.com/boxen/puppet-vagrant/compare/3.3.0...3.3.4 looks fine to me.

Note that the docs say the default version is bumped from 1.7.2 but the default version is actually 1.8.0 (docs are wrong, boxen/puppet-vagrant#67).

**Comment by bradwright** [comment]
Do we need to fix this, too?

https://github.com/alphagov/gds-boxen/blob/master/modules/gds_development/manifests/init.pp#L7

**Comment by dcarley** [comment]
> Do we need to fix this, too?
> 
> https://github.com/alphagov/gds-boxen/blob/master/modules/gds_development/manifests/init.pp#L7

Not sure. It'll continue to work as is. In fact, people that have included that class won't experience any change of version, because that takes precedence over the `include vagrant`.

**Comment by bradwright** [comment]
Maybe 'fix' is the wrong word. Should we upgrade the Vagrant version there as well?

**Comment by timmow** [comment]
I'm going to merge this and we can raise a separate PR if we want to update the version in gds_development

**Pull request merged**
