### PR TITLE
Add 3rd floor printer

### PR DESCRIPTION
**Pull request by daibach**
Add the 3rd floor printer to `gds_printers` so we don't have to walk to the 6th floor.

### CODE REVIEW

**Comment by dcarley** [comment]
Was really hoping that someone was going to do this, because I was getting tired of walking to the 6th floor. Thanks :+1:

**Comment by daibach** [comment]
:+1:

**Comment by rjw1** [comment]
@dcarley arnt you upstairs on the 7th though /cc @annashipman

**Comment by dcarley** [comment]
Haven't been for over a month. Keep up!

**Comment by annashipman** [comment]
I can't keep up...

**Pull request merged**
