### PR TITLE
Module updates (20150223)

### PR DESCRIPTION
**Pull request by samjsharpe**
Module updates (20150223)

Performs the following updates:
```
- boxen       "3.7.0" -> "3.9.1"
- dnsmasq     "2.0.0" -> "2.0.1"
- homebrew    "1.9.8" -> "1.11.6"
- module_data "0.0.3" -> "0.0.4"
- git         "2.7.1" -> "2.7.5"
- hub         "1.3.0" -> "1.4.0"
- inifile     "1.1.3" -> "1.2.0"
- java        "1.7.0" -> "1.8.0"
- nginx       "1.4.3" -> "1.4.5"
- ruby        "8.1.4" -> "8.3.1"
- stdlib      "4.3.2" -> "4.5.1"
- alfred      "1.3.1" -> "1.4.0"
- android     "1.3.0" -> "1.4.0"
- atom        "1.0.0" -> "1.2.0"
- brewcask    "0.0.4" -> "0.0.5"
- concat      "1.0.0" -> "1.2.0"
- dropbox     "1.4.0" -> "1.4.1"
- evernote    "2.0.6" -> "2.0.7"
- emacs       "1.1.6" -> "2.0.0"
- iterm2      "1.2.2" -> "1.2.4"
- mysql       "1.2.2" -> "1.99.91"
- osx"        "2.7.1" -> "2.8.0"
- qt          "1.3.1" -> "1.4.0.pre2"
- skype       "1.0.9" -> "1.1.0"
- vagrant     "3.2.0" -> "3.2.2"
```

Runs cleanly for me, however I don't use the android, atom, evernote, mysql or qt modules.

### CODE REVIEW

**Comment by samjsharpe** [comment]
Bump!

**Comment by KushalP** [comment]
I think all of this is good and have run it locally on Yosemite. Anyone else running on Mavericks had a chance to have a look?

**Comment by alexmuller** [comment]
Runs for me on Mavericks and changes some stuff :+1:

**Comment by alexmuller** [comment]
On second thoughts, this breaks all of Homebrew and Git :skull:

**Comment by samjsharpe** [comment]
@bradleywright you'll love this...

```
[Projects/gds-boxen:mod-update-20150209●]$ hub --version
git version 1.9.3 (Apple Git-50)
hub version 2.2.0
[Projects/gds-boxen:mod-update-20150209●]$ file `which hub`
/opt/boxen/homebrew/bin/hub: Mach-O 64-bit executable x86_64
```

Git just got fast again...

**Comment by samjsharpe** [comment]
Really? Hmm. Breaks how?

**Comment by alexmuller** [comment]
A bit like this:

```
Last login: Mon Feb 23 12:18:11 on ttys006
-bash: hub: command not found
-bash: brew: command not found
-bash: brew: command not found
-bash: __git_ps1: command not found
[HOST] 12:23:17 ~ $ brew
-bash: brew: command not found
-bash: __git_ps1: command not found
[HOST] 12:23:20 ~ $ hub
-bash: hub: command not found
-bash: __git_ps1: command not found
[HOST] 12:23:26 ~ $ git
-bash: hub: command not found
-bash: __git_ps1: command not found
[HOST] 12:23:27 ~ $ grep __git_ps1 .bash_profile 
PS1="\[$BOLDGREEN\][HOST]\[$RESET\] \t \w\$(__git_ps1) $ "
-bash: __git_ps1: command not found
```

I'm not really sure what's going on but it looks like those commands are no longer installed.

**Comment by samjsharpe** [comment]
Hrm... Git is usually aliased to Hub. Hub has fundamentally changed from Ruby to Go and possibly moved around a bit. Does that change if you start a new shell instead?

**Comment by samjsharpe** [comment]
Oh actually that must be a new shell, as I can see your `last login` output. Ok, I don't know why that's broken. Not sure if you have them installed but your shell just can't find them?

**Comment by rjw1** [comment]
i see the same issues :)
```
bobwalker@GDS479:~ ☃>bash
bash: hub: command not found
bash: brew: command not found
bash: gpg-agent: command not found
```

there is a path issue somewhere

**Comment by alexmuller** [comment]
Path diff:

```diff
-bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/munki
+bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/munki
```

**Comment by rjw1** [comment]
yeah /opt/boxen/homebrew/bin and sbin went away.

**Comment by rjw1** [comment]
i added 
```
PATH=$PATH:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin
```
before
```
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
```
in my `.bashrc` and everything seems good now

**Comment by rjw1** [comment]
```diff
Notice: /Stage[main]/Boxen::Config/File[/opt/boxen/env.sh]/content:
--- /opt/boxen/env.sh	2013-11-18 12:43:06.000000000 +0000
+++ /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/puppet-file20150223-33964-1gnh5b2-0	2015-02-23 12:18:20.000000000 +0000
@@ -11,14 +11,6 @@

 export BOXEN_HOME=/opt/boxen

-# Add homebrew'd stuff to the path.
-
-PATH=$BOXEN_HOME/homebrew/bin:$BOXEN_HOME/homebrew/sbin:$PATH
-
-# Add homebrew'd stuff to the manpath.
-
-export MANPATH=$BOXEN_HOME/homebrew/share/man:$MANPATH
-
 # Add any binaries specific to Boxen to the path.

 PATH=$BOXEN_HOME/bin:$PATH
```
seems relevant

**Comment by samjsharpe** [comment]
That's interesting - I already set those things in my path:
```
#Exports
PATH=$PATH:/usr/local/sbin:/usr/local/bin
PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
PATH=$PATH:/Applications/Vagrant/bin:/opt/boxen/homebrew/bin:~/.bin
PATH=$PATH:~/Projects/go/bin:/opt/boxen/homebrew/Cellar/go/1.2.2/libexec/bin/
export PATH

source_if_exists $ZSH/oh-my-zsh.sh
source_if_exists /opt/boxen/env.sh
```

**Comment by rjw1** [comment]
https://github.com/boxen/puppet-boxen/commit/a1c7b2bbd30e2553a6d633c5e317742fdc6445b6

**Comment by samjsharpe** [comment]
Awesome. Standby for a fix!

**Comment by rjw1** [comment]
these pesky open source people and their changes

**Comment by samjsharpe** [comment]
Now also upgrades Homebrew. Try again!

**Comment by rjw1** [comment]
looks good to me. commit message is now wrong though :)

**Comment by samjsharpe** [comment]
All the dates and versions in comments are now updated..

**Pull request merged**
