### PR TITLE
remove gds_resolver

### PR DESCRIPTION
**Pull request by philandstuff**
Long ago, this module was created to resolve issues hitting our internal
DNS server.  However, at some point, 192.168.19.254 stopped being a
valid internal DNS server -- or at least, it's not valid on all networks.
So this module only has the effect of breaking internal DNS.

People have worked around this broken DNS (say, by having /etc/hosts
entries for frequently-used hostnames) which may be why this brokenness
has gone unfixed.  But it's probably time to remove it.

People who use this module: @bradwright @bruntonspall @carlmassa @daibach @dcarley @heathd @issyl0 @jennyd @JohnStrudwick @mattbostock @robyoung @russellthorn @surminus @tombooth

### CODE REVIEW

**Comment by dcarley** [comment]
:ok_hand:

**Comment by timmow** [comment]
:ok_hand:

**Comment by bradwright** [comment]
:+1:

**Comment by JohnStrudwick** [comment]
:+1:

**Comment by surminus** [comment]
:+1:

**Comment by daibach** [comment]
:+1:

**Comment by tombooth** [comment]
:+1:

**Comment by carlmassa** [comment]
emoticon indicating agreement

On 15 January 2016 at 15:16, Tom Booth <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/gds-boxen/pull/199#issuecomment-171988444>.
>



-- 
Carl Massa
Government Digital Service
Aviation House
125 Kingsway
London
WC2B 6NH

carl.massa@digital.cabinet-office.gov.uk

**Comment by philandstuff** [comment]
I think that's a quorum. does someone want to merge?

**Pull request merged**
