### PR TITLE
Removed samjsharpe/puppet-ohmyzsh

### PR DESCRIPTION
**Pull request by rjbate**

### CODE REVIEW

**Comment by timmow** [comment]
This is still referenced in people manifests -

```
modules/people/manifests/dcarley.pp
16:  include ohmyzsh

modules/people/manifests/mattbostock.pp
16:  include ohmyzsh

modules/people/manifests/robyoung.pp
9:  include ohmyzsh

modules/people/manifests/surminus.pp
13:  include ohmyzsh
```

And is also referenced in the `Puppetfile.lock`

It might be ok to change to [this module](https://github.com/erivello/puppet-ohmyzsh) but you'd need to check with @surminus and @dcarley as they seem to be using the module

**Comment by rjbate** [comment]
I'm running in to the same issues encountered here: https://github.com/alphagov/gds-boxen/issues/208

Some of the repos have been removed and cause the script to bug out.

It looks additionally as though I need to remove samjsharpe/puppet-spf13vim3

**Comment by rjbate** [comment]
Ah. Looks like Sam has moved his stuff here:

https://libraries.io/github/samjsharpe/

**Comment by rjbate** [comment]
Closing this PR as I think the right approach is to modify the Puppetfile to find the modules in their new location.

**Pull request closed without merging**
